### ISSUE TITLE
"--series xenial" completely broken in latest release

### ISSUE THREAD

**Issue by Vultaire** [juju-solutions/charm-ubuntu#45] opened 2022-07-14 19:11 UTC
"--series xenial" appears to be completely broken.

This appears to be a possible issue in Operator Framework.  The logs I get look like this:

```
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60 Traceback (most recent call last):
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "./src/charm.py", line 7, in <module>
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     from ops.charm import CharmBase
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/var/lib/juju/agents/unit-ubuntu-xenial-0/charm/venv/ops/__init__.py", line 43, in <module>
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     from . import charm  # noqa: F401 (imported but unused)
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/var/lib/juju/agents/unit-ubuntu-xenial-0/charm/venv/ops/charm.py", line 22, in <module>
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     from ops import model
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/var/lib/juju/agents/unit-ubuntu-xenial-0/charm/venv/ops/model.py", line 1239, in <module>
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     class Container:
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/var/lib/juju/agents/unit-ubuntu-xenial-0/charm/venv/ops/model.py", line 1395, in Container
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     level: Optional['pebble.CheckLevel'] = None) -> 'CheckInfoMapping':
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     return Union[arg, type(None)]
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     dict(self.__dict__), parameters, _root=True)
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/usr/lib/python3.5/typing.py", line 512, in __new__
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     self._eval_type(globalns, localns)
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60     eval(self.__forward_code__, globalns, localns),
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60   File "<string>", line 1, in <module>
2022-07-14 18:52:56 WARNING unit.ubuntu-xenial/0.install logger.go:60 AttributeError: 'property' object has no attribute 'CheckLevel'
2022-07-14 18:52:56 ERROR juju.worker.uniter.operation runhook.go:140 hook "install" (via hook dispatching script: dispatch) failed: exit status 1
2022-07-14 18:52:56 INFO juju.worker.uniter resolver.go:144 awaiting error resolution for "install" hook
```

**Comment by Vultaire** [comment] 2022-07-14 19:12
This appears to be a known operator framework bug from 2 days ago: https://github.com/canonical/operator/issues/798

**Comment by spads-spads** [comment] 2022-07-20 11:36
This was a nasty surprise to hit on an upgrade-charm hook.

**Comment by spads-spads** [comment] 2022-07-20 13:33
The workaround right now is:

```bash
$ juju refresh $appname --revision=19
$ juju resolve $appname/0 $appname/1 [...]
```

We have also had to update our bundles to pin `cs:ubuntu-19` on all Xenial units.

**Comment by agileshaw** [comment] 2022-08-05 22:49
Just hit the same issue today. There's a [PR](https://github.com/canonical/operator/pull/810) submitted today aiming to solve [this operator framewok issue](https://github.com/canonical/operator/issues/798). Hopefully it will get merged soon.

**Comment by PietroPasotti** [comment] 2022-08-10 08:43
If @agileshaw or @spads-spads had time to check that https://github.com/canonical/operator/pull/810 indeed solves the issue, we're ready to merge

**Comment by agileshaw** [comment] 2022-08-11 20:22
@PietroPasotti I have built and packed charm-ubuntu with your ops changes. Unfortunately, it didn't resolve the issue
```
$ cat requirements.txt 
#ops>=1.0,<2.0
git+https://github.com/PietroPasotti/operator.git#egg=ops

$ juju deploy ./ubuntu_ubuntu-16.04-amd64_ubuntu-18.04-amd64_ubuntu-20.04-amd64_ubuntu-22.04-amd64.charm --series=xenial
Located local charm "ubuntu", revision 0
Deploying "ubuntu" from local charm "ubuntu", revision 0 on xenial

$ juju debug-log --replay --include ubuntu/2
...
unit-ubuntu-2: 20:18:10 WARNING unit.ubuntu/2.install AttributeError: 'property' object has no attribute 'CheckLevel'
unit-ubuntu-2: 20:18:10 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1

```

**Comment by agileshaw** [comment] 2022-08-12 00:18
Hello @PietroPasotti, I've built and packed charm-ubuntu with your changes in operator framework. It _indeed_ solves the issue. Thank you for the fix. I apologize for the confusion in my previous comment (deleted) where I was testing on a wrong branch.

```
$ cat requirements.txt 
#ops>=1.0,<2.0
git+https://github.com/PietroPasotti/operator@fix-model-types#egg=ops

$ juju deploy ./ubuntu_ubuntu-16.04-amd64_ubuntu-18.04-amd64_ubuntu-20.04-amd64_ubuntu-22.04-amd64.charm --series=xenial
Located local charm "ubuntu", revision 1
Deploying "ubuntu" from local charm "ubuntu", revision 1 on xenial

$ juju status
Model  Controller                   Cloud/Region                 Version  SLA          Timestamp
test   openstack-cloud-serverstack  openstack-cloud/serverstack  2.9.29   unsupported  00:13:04Z

App     Version  Status  Scale  Charm   Channel  Rev  Exposed  Message
ubuntu  16.04    active      1  ubuntu             1  no       

Unit       Workload  Agent  Machine  Public address  Ports  Message
ubuntu/3*  active    idle   3        10.5.2.157             

Machine  State    Address     Inst id                               Series  AZ    Message
3        started  10.5.2.157  d3ddb774-7c0e-4199-be85-a4a9429f9a25  xenial  nova  ACTIVE


```

**Comment by agileshaw** [comment] 2022-09-08 18:17
The problem is still present when deploying the charm directly from charmhub because it still pulls ops-1.5.0 as a dependency. 

```
ubuntu@juju-6c075c-test2-0:/var/lib/juju/agents/unit-ubuntu-0/charm/venv$ ls
easy_install.py      pip                   pkg_resources-0.0.0.dist-info  setuptools                   _yaml
ops                  pip-20.0.2.dist-info  __pycache__                    setuptools-44.0.0.dist-info
ops-1.5.0.dist-info  pkg_resources         PyYAML-6.0.dist-info           yaml
```

**Comment by jneo8** [comment] 2022-09-15 03:35
Same issue as @agileshaw when deploy xenial series

**Comment by agileshaw** [comment] 2022-09-15 15:23
The issue got resolved with [revision 21](https://charmhub.io/ubuntu).

**Closed by agileshaw** 2022-09-15 15:23 UTC
